export const add = (a: number, b: number): number => a + b;
export const subtract = (a: number, b: number): number => a - b;
export const multiply = (a: number, b: number): number => a * b;
export const divide = (a: number, b: number): number => b !== 0 ? a / b : NaN;
export const modulus = (a: number, b: number): number => a % b;
export const increment = (a: number): number => a + 1;
export const decrement = (a: number): number => a - 1;
export const square = (a: number): number => a * a;
export const cube = (a: number): number => a * a * a;
export const power = (base: number, exponent: number): number => Math.pow(base, exponent);
export const sqrt = (a: number): number => Math.sqrt(a);
export const cbrt = (a: number): number => Math.cbrt(a);
